package com.skillspherenexus.certificationmanagementservice.enums;

public enum AuditAction {
    REGISTERED, UPDATED, IMPORTED_FROM_M1, STATUS_EVALUATED, REVOKED, RENEWAL_REQUESTED, RENEWAL_APPROVED, RENEWAL_REJECTED, NOTIFICATION_SENT, NOTIFICATION_ACKNOWLEDGED, COMPLIANCE_VERIFIED, VERIFICATION_UPDATED
}
